consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:3000
info:
  description: A teser for go
  title: The adder API
  version: ""
paths: {}
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
