consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:3000
info:
  description: A teser for go
  title: The adder API
  version: ""
paths:
  /:
    get:
      description: add returns the sum of the left and right parameters in the response
        body
      operationId: operands#add
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: add operands
      tags:
      - operands
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
