// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application Media Types
//
// Command:
// $ goagen
// --design=playground/micro/design
// --out=$(GOPATH)/src/playground/micro
// --version=v1.3.1

package app
