// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=micro/design
// --out=$(GOPATH)/src/micro
// --version=v1.3.1

package app
